Repository TheArkStation/Ark-Station, pull requests merged in 2019-11, with the labels that each got.

#136 Возвращаем лоадаут резоми
  baystation12.dme
Labels: Fix

#138 Репутация
  baystation12.dme
  code/game/world.dm
  code_ark/code/datums/reputation.dm
  code_ark/code/modules/client/reputation.dm
  code_ark/modules/client/client_defines.dm
  code_ark/modules/client/client_procs.dm
Labels: Feature

#139 Обновляем Vote Panel
  code/controllers/subsystems/vote.dm
  code/datums/vote/gamemode.dm
  code/datums/vote/vote.dm
  code/modules/client/client_procs.dm
Labels: Feature

#144 Prometheus-Tweak
  maps/castelnau/castelnau_overmap.dm
Labels: (Re)balance

#158 Ф и к с и к и
  code/_helpers/text.dm
  code/controllers/subsystems/initialization/fabrication.dm
  code/datums/outfits/outfit.dm
  code/game/objects/items.dm
  code/modules/client/preference_setup/loadout/lists/storage.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/modular_computers/hardware/card_slot.dm
  code/modules/research/rdconsole.dm
  interface/interface.dm
  maps/castelnau/castelnau-1.dmm
  maps/castelnau/castelnau_shuttles.dm
  maps/castelnau/loadout/loadout_utility.dm
  maps/castelnau/structures/sofa.dm
Labels: Fix

#159 Human topic
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature

#164 Убираем лишний таб
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#140 Цветные лампочки
  baystation12.dme
  code/modules/materials/material_recipes.dm
  code_ark/code/game/machinery/lightcolorswitch.dm
  code_ark/code/game/objects/items/buttons.dm
  code_ark/code/modules/fabrication/designs/general/designs_general.dm
  code_ark/code/modules/materials/recipes_items.dm
  code_ark/code/modules/power/lighting.dm
  code_ark/icons/obj/power.dmi
Labels: Feature

#171 Закрываем унатхам доступ к капитану и первому помощнику
  maps/castelnau/job/jobs.dm
Labels: (Re)balance

#145 Двойные кровати
  baystation12.dme
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code_ark/code/game/objects/structures/bedsheet_bin.dm
  code_ark/code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code_ark/icons/obj/bedsheet.dmi
  code_ark/icons/obj/furniture.dmi
Labels: Feature, Icons
